name: build-wheels.yaml

on:
  push:
    branches: [feature/build-wheels-pypi-dist]
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Only for installing cibuildwheel; cibuildwheel handles all versions

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir dist

        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
          CIBW_SKIP: "*-musllinux*"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ENVIRONMENT: "CXXFLAGS='-std=c++20'"

      - uses: actions/upload-artifact@v4
        with:
          name: built-wheels
          path: dist

