name: build-wheels.yaml

on:
  push:
    branches: [feature/build-wheels-pypi-dist]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Optional: Upgrade pip/build tools
      - name: Upgrade build dependencies
        run: python -m pip install --upgrade pip build setuptools wheel numpy

      # ----------- Linux & macOS: Install fmt via system -----------
      - name: Install fmt (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libfmt-dev

      - name: Install fmt (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install fmt

      # Windows: requires fmt to be pre-installed or vendored (TODO if needed)

      # ----------- Build the wheel -----------
      - name: Build wheel
        run: python -m build

      # Upload the wheel
      - uses: actions/upload-artifact@v4
        with:
          name: genomekit-wheels-${{ matrix.os }}
          path: dist/*.whl

#jobs:
#  build_wheels:
#    name: Build wheels on ${{ matrix.os }}
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest]
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.12'  # Only for installing cibuildwheel; cibuildwheel handles all versions
#
#      - name: Install cibuildwheel
#        run: python -m pip install cibuildwheel
#
#      - name: Build wheels
#        run: python -m cibuildwheel --output-dir dist
#
#        env:
#          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
#          CIBW_SKIP: "*-musllinux*"
#          CIBW_ARCHS_MACOS: "x86_64 arm64"
#          CIBW_ENVIRONMENT: "CXXFLAGS='-std=c++20'"
#
#      - uses: actions/upload-artifact@v4
#        with:
#          name: built-wheels
#          path: dist
#
